### PR TITLE
style: remove comment for readability

### PR DESCRIPTION
**Pull request by techemmy**
This PR should resolve issue #84

### CODE REVIEW

**Comment by GabrielCTroia** [comment]
Hey @techemmy this is almost ready to merge! Thank you so much for your effort, but before I can merge it could you please sign your commit as described here https://docs.github.com/articles/about-gpg/

**Comment by techemmy** [comment]
Hi @GabrielCTroia, I've signed the commit already

**Comment by GabrielCTroia** [comment]
Hey @techemmy, this is what a verified commit normally looks like:
Screenshot 2023-10-11 at 2 04 46 PM
or
Screenshot 2023-10-11 at 2 05 08 PM

From my side I can merge it like this without a problem, it's just that github won't be able to track your contribution for hacktoberfest 😔

**Comment by techemmy** [comment]
> Hey @techemmy, this is what a verified commit normally looks like: Screenshot 2023-10-11 at 2 04 46 PM or Screenshot 2023-10-11 at 2 05 08 PM
> 
> From my side I can merge it like this without a problem, it's just that github won't be able to track your contribution for hacktoberfest 😔

I signed it already. Is there any thing I am missing? Do you have any guide on how I can sign it?

**Comment by GabrielCTroia** [comment]
> > Hey @techemmy, this is what a verified commit normally looks like: Screenshot 2023-10-11 at 2 04 46 PM or Screenshot 2023-10-11 at 2 05 08 PM
> > From my side I can merge it like this without a problem, it's just that github won't be able to track your contribution for hacktoberfest 😔
> 
> I signed it already. Is there any thing I am missing? Do you have any guide on how I can sign it?

Sure, check this out https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by techemmy** [comment]
Does this work? One of the commits is signed.

**Comment by GabrielCTroia** [comment]
See my suggestion on your other PR https://github.com/movesthatmatter/movex/pull/108#issuecomment-1758606175

**Comment by techemmy** [comment]
I think you should merge this one as is.

**Pull request merged**
