### PR TITLE
Add favicon to document

### LINKED ISSUE #83: [apps/movex-docs] Add favicon to Next app
# Where 

`apps/movex-docs`

# What

Add this logo `https://github.com/movesthatmatter/movex/blob/main/art/x_logo_a.png` as a fav icon for the movex-docs next app.

You will need to create new icons probably using something like https://favicon.io/ or similar.

# Why

Because currently it's blank

# Definition of done
- [ ] the fav icon works on all platforms (desktop, mobile)
- [ ] all tests pass `yarn test`

### PR DESCRIPTION
**Pull request by chanon-mike**
## Related Issue
Close #83 

## Summary
Add `https://github.com/movesthatmatter/movex/blob/main/art/x_logo_a.png` as a fav icon for the movex-docs next app.

## Test cases
- [x] fav icon appears on all platforms (desktop, mobile)
- [x] `yarn test` pass

## Screenshot
image

### CODE REVIEW

**Comment by GabrielCTroia** [comment]
Aweomse @chanon-mike! Will this work on all the browser & mobile as well?

**Comment by chanon-mike** [comment]
> Awesome @chanon-mike! Will this work on all the browser & mobile as well?

@GabrielCTroia It should have work. 
I tested in chrome, safari, firefox and edge in my pc, and my android also appear fine.

**Comment by GabrielCTroia** [comment]
Ok, great @chanon-mike! One last thing before I can merge – could you please sign your commit like is described here https://docs.github.com/articles/about-gpg/! 🙏

**Comment by chanon-mike** [comment]
@GabrielCTroia Thank you!
I signed a commit now, please check.

**Comment by GabrielCTroia** [comment]
Merged! Thank you so much @chanon-mike for your effort!

One last thing, could you please give the repo a star so we can bump it up the #hacktoberfest ladder today! 😁🙏🚀

**Comment by GabrielCTroia** [comment]
Hey @chanon-mike, thanks for the star!

I checked your github profile a bit and noticed you built this cool game https://github.com/chanon-mike/online-othello! Congrats! 🎉

I was curios how easy would it be to try it on Movex, since this is exactly what Movex is attempting to offer solutions for. You could just use the `movex-react` library since your it's already build in nextjs. 🤔

Let me know your thoughts! 🙌

**Comment by chanon-mike** [comment]
@GabrielCTroia Thank you for looking into my profile! 
I think that's really interesting idea! I will try to do that if I have time!

**Comment by GabrielCTroia** [comment]
> @GabrielCTroia Thank you for looking into my profile! I think that's really interesting idea! I will try to do that if I have time!

Thank you so much for considering it! I'd love to see how it goes. 

Also if you need my help in any way don't hesitate to write me. You can also join our discord to talk more and show you what I have built with it as well! 🙌

**Pull request merged**
