### PR TITLE
imported the md5 function instead of the whole object-hash

### LINKED ISSUE #30: Use a smaller object hashing lib/function
# What

Currently we use the [object-hash](https://www.npmjs.com/package/object-hash) library to hash the state object and get an accurate hash/token both on the client and the server (node).

This is a very important feature that sits at the core of movex - being able get a hash/token of current state both on the client and the server, which makes the state synchronization possible with minimum data sent over the wire and minimum trips. For more info see https://www.movex.dev/docs/how/state_synchronization.

# Why 

To reduce the library size!

The problem at the moment with object-hash is that it's too big, making for 17.5% of the whole movex library. That is party because we import the whole object-hash but only use the md5 function.

Screenshot 2023-10-05 at 6 48 37 PM
Source: https://bundlephobia.com/package/movex@0.1.2

# Definition of done

- start using a different hashing/md5-ing library or add the hashing function to the library
- VERY IMPORTANT: the resulted hash/token is the same when run in the browser AND on the server (node)
- All tests are passing `yarn test`
- The library decreased in size

### PR DESCRIPTION
**Pull request by Ekep-Obasi**
Fixes #30

**Checks**

- [x] resulted hash/token is the same when run in the browser AND on the server (node)
 - [x] All tests are passing `yarn test`
 - [x] The library decreased in size

### CODE REVIEW

**Review by GabrielCTroia — APPROVED** [review]
Approved!

**Comment by GabrielCTroia** [comment]
Thank you @Ekep-Obasi! Your PR is ready to be merged. 

The only thing left is if you could sign your commits. See here how https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by Ekep-Obasi** [comment]
Thank you @GabrielCTroia 
I have signed the commit

**Comment by GabrielCTroia** [comment]
Merged 🎉🚀! Thank you so much @Ekep-Obasi!

Could give us a star as well please so we can bump the rep up a bit!🙏

**Comment by Ekep-Obasi** [comment]
Yeah sure ☺️

**Pull request merged**
