### PR TITLE
Safely Removed resourceFile.ts issue #31

### PR DESCRIPTION
**Pull request by tvermaashutosh**
issue #31 

Since the `libs/movex/src/lib/tools/resourceFile.ts` isn't used anymore I safely removed it.

### CODE REVIEW

**Comment by GabrielCTroia** [comment]
Hey @tvermaashutosh thanks for your PR. I just checked and the tests are failing. Did you run `yarn test`?

I think one or more import is still there!

**Comment by GabrielCTroia** [comment]
Hey @tvermaashutosh, are you still on this? Let me know if you need any help with it – it seems at the moment it has some conflicts with the current main!

Here to help if you need anything 🙏

**Comment by tvermaashutosh** [comment]
No @GabrielCTroia I am not working on this issue anymore sorry.

**Comment by GabrielCTroia** [comment]
@Abhishek-Mallick would you like to take this whenever you have a chance?

**Comment by Abhishek-Mallick** [comment]
@GabrielCTroia  Sure
Assign it to me

**Comment by GabrielCTroia** [comment]
I merged this by mistake 🤓

**Comment by GabrielCTroia** [comment]
But somehow it seems to not break the tests. I'm a bit confused why was this not merged before 🧐

**Pull request merged**
