### PR TITLE
clean up CoreTypes file of commented code

### PR DESCRIPTION
**Pull request by Franqsanz**
The comments described in the problem were removed: #23

### CODE REVIEW

**Review by GabrielCTroia — APPROVED** [review]
Thank you! Approved 🚀

**Comment by GabrielCTroia** [comment]
Hey @Franqsanz, this is ready to merge! Thank you 🙏

One last step, could you please sign your commit before I can merge it? See what I mean here https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by Franqsanz** [comment]
Yes, no problem, but I will do it on Monday, if you don't mind, thank you!

**Comment by GabrielCTroia** [comment]
Sure @Franqsanz, no worries!

**Comment by Franqsanz** [comment]
Hello @GabrielCTroia, good morning, how do I sign the current commit or should I upload a new one, I have already generated my password.

**Comment by GabrielCTroia** [comment]
If you have signed the commit locally, you can just push it again here using `git push -f` to force it to override the previous one! 

Let me know if you have issues and thank you! Looking forward to merge this in 🙏

**Comment by Franqsanz** [comment]
I can't figure out how to sign a commit already uploaded in github, I've tried as you mentioned but nothing happens. Maybe I'm skipping some step. 😅

**Comment by GabrielCTroia** [comment]
Hey, no worries – I'm sure that's annoying! :)

It's this commit that needs to be signed as well [clean up CoreTypes file of commented code](https://github.com/movesthatmatter/movex/pull/33/commits/4e7bcf73d2a619b85e9bcb801da91210e62f4b03), not a future one. 

Sorry for the hassle is this https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification not describing well enough?

**Comment by GabrielCTroia** [comment]
> Hey, no worries – I'm sure that's annoying! :)
> 
> It's this commit that needs to be signed as well [clean up CoreTypes file of commented code](https://github.com/movesthatmatter/movex/pull/33/commits/4e7bcf73d2a619b85e9bcb801da91210e62f4b03), not a future one.
> 
> Sorry for the hassle is this https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification not describing well enough?

Try this: `git rebase --exec 'git commit --amend --no-edit -n -S' -i YOUR_BRANCH`

**Comment by Franqsanz** [comment]
Well I think I've done it now, sorry for all this lost time, it's the first time I use commit signed! thanks for your patience.

**Comment by GabrielCTroia** [comment]
Yep, no worries! Running the tests one more time and I'm ready to merge it! 
Thank you so much for your effort and patience as well! 🙏

I'm curios if you have any feedback for the project:
- was it easy to get around the codebase and understand?
- did you understand the docs?
- do you have any suggestions for improvements?

**And lastly, could you please give us a star so we can bump the repo up a bit!?** 

Thank you once more! ❤️🙏🚀

**Pull request merged**
