### PR TITLE
Clean ups

### LINKED ISSUE #42: [libs/movex-react] Clean up `hooks.ts` file
# Where

`libs/movex-react/src/lib/hooks.ts`

# What

This file as a bunch of commented code that's not useful anymore and can be removed

# Why
Readablity 

# Definition of done
- The commented code is removed
- The comment that says TODO on line 120 should stay!

### PR DESCRIPTION
**Pull request by Ekep-Obasi**
Fixes #42

Checks:

I removed commented code in `libs/movex-react/src/lib/hooks.ts` to improve readability

- [x] The commented code is removed
- [x] The comment that says TODO on line 120 still remains
- [x] proper indentation

### CODE REVIEW

**Comment by GabrielCTroia** [comment]
Hi @Ekep-Obasi! Please check the conflicting files here – you might need to do rebase! 

Let me know if you need help with that!

**Comment by Ekep-Obasi** [comment]
@GabrielCTroia I noticed that all my commits aggregate
How do I deal with that?

**Comment by GabrielCTroia** [comment]
Hmm, make sure you branch off of master for each new issues, rather than from the previous committed change you've made.

**Comment by Ekep-Obasi** [comment]
@GabrielCTroia  
Done !

**Comment by GabrielCTroia** [comment]
Thank you! 🙏

**Pull request merged**
