### PR TITLE
imported only used methods from fast-json-patch

### LINKED ISSUE #43: Decrease the library size by importing only needed methods from `fast-json-patch`
# Where

`libs/movex/src/lib/util.ts`

# What

Instead of importing the whole package as on the 1st line in the screen shot below, import only the used ones!
Screenshot 2023-10-06 at 7 50 23 PM

# Definition of done
- [ ] the file size decreased
- [ ] all tests pass `yarn test`

### PR DESCRIPTION
**Pull request by Ekep-Obasi**
Fixes #43 

imported only needed methods from fast-json-patch to decrease library size

Checks:

 - [x] the file size decreased
 - [x] all tests pass yarn test

### CODE REVIEW

**Comment by Ekep-Obasi** [comment]
@GabrielCTroia  I think this is okay now

**Comment by GabrielCTroia** [comment]
Hey @Ekep-Obasi, thanks for signing the commit. I'm ready to merge it but it seems it has a few small conflicts.

Could you run a git rebase over the updated `main` and solve those. Then I'm ready to merge! Thanks

**Comment by Ekep-Obasi** [comment]
@GabrielCTroia 
 I've resolved conflicts

**Comment by GabrielCTroia** [comment]
Thank you! 

It seems the tests are failing though 🤔. Can you please take a look

Screenshot 2023-10-09 at 4 46 29 PM

**Comment by Ekep-Obasi** [comment]
Oh, I see the problem

**Pull request closed without merging**
