### PR TITLE
Removed self referencing absolute imports [libs/movex-react]

### LINKED ISSUE #38: [libs/movex-react] Remove self referencing absolute imports
# Where

`/libs/movex-react`

# What

There are a few imports that are directly referencing the absolute "movex-react" path (i.e. from node_modules) instead of importing from a relative path, since it's within it's directory!

See the culprit files here:

Screenshot 2023-10-06 at 6 57 13 PM

# Why
This is not ideal because it can create more importing issues down the road. It's also not necessary!

# Definition of done

- All the absolute imports aka `import { my_file } from 'movex-react'` is changed to `import { my_file } from './path/to/my_file'`
- Note, these only refers to imports from 'movex-react' not any of the other libraries such as 'movex', 'movex-core-util', etc.

### PR DESCRIPTION
**Pull request by ikunal-04**
Fixes #38 
Hey @GabrielCTroia I'm requesting to review my changes. Please let me know if you have any feedback.

### CODE REVIEW

**Comment by GabrielCTroia** [comment]
Hey @ikunal-04! Thank you for your changes - it looks good and I'm about to merge. One last step before I do, can you please sign your commit? Check this if you have issues https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by ikunal-04** [comment]
Hey @GabrielCTroia by reading this docs I'm able to sign my commit locally and I have verified it, now I'm only having issues to push my locally signed commit to the github?

**Comment by GabrielCTroia** [comment]
You can force push like `git push -f`

**Comment by ikunal-04** [comment]
It worked @GabrielCTroia. Now my commit is signed! 😊👍

**Comment by ikunal-04** [comment]
Hey @GabrielCTroia I'm assuming that my PR is good to merge but still if there is any feedback, please let me know! 😊

**Pull request merged**
