### PR TITLE
Movex service add nx runner for tsc compiler

### PR DESCRIPTION
**Pull request by techemmy**
To resolve issue #101

### CODE REVIEW

**Comment by GabrielCTroia** [comment]
Hey @techemmy, it seems like you brought all of your commits from the previous PR as well. could you please close branch off of main with a new branch and then add your commit (last here) that solves this issue? 🙏

This way we keep things clean and easy to read! 🙌

**Comment by techemmy** [comment]
Do you mean I should create a new branch and move the commit there? That would mean I have to create another PR, right?

**Comment by GabrielCTroia** [comment]
> Do you mean I should create a new branch and move the commit there? That would mean I have to create another PR, right?

Yessir, that would be the easiest! Once you create the new PR you can also close this one!

**Comment by GabrielCTroia** [comment]
Closing this one!

**Pull request closed without merging**
