### PR TITLE
Fix Linting

### LINKED ISSUE #129: [libs/movex-core-util] Fix linting Errors in File: `types.ts`
# Where 

`libs/movex-core-util/src/lib/core-util/types.ts`

# What

When you run `npx nx lint movex-core-util --quiet` you get some errors as below:

Screenshot 2023-10-13 at 1 54 04 PM

# Why is it important

Because in the close future, the linting command will be part of the Github Actions

# Definition of done
- running `npx nx lint movex-core-util --quiet` will not return any more errors for this file
- tsc passes `npx nx tsc movex-core-util`
- all tests pass `yarn lint`
- no unnecessary code is introduced

### PR DESCRIPTION
**Pull request by Rounak-stha**
Fixes #129

### CODE REVIEW

**Comment by Rounak-stha** [comment]
Hey,
even though this does not result in a level 1 (warn) error, if there's no any specific reason to use any, we could use `unknown`.
I did a global search and didn't see the type being used yet.
wanted to confirm!

**Comment by Rounak-stha** [comment]
Also, there's this issue.
image

And there's no file specified in the workflow too.

**Comment by GabrielCTroia** [comment]
Thank you @Rounak-stha!

**Comment by GabrielCTroia** [comment]
> Hey, even though this does not result in a level 1 (warn) error, if there's no any specific reason to use any, we could use `unknown`. I did a global search and didn't see the type being used yet. wanted to confirm!

What's the warn about? Could you paste a screen shot?

**Comment by Rounak-stha** [comment]
> What's the warn about? Could you paste a screen shot?

Yeah, I had a typo, I meant eslint warns (level 1) on the use of `any`.

I am not 100% sure if `unknown` is really what I want here but wanted to make sure if there is a possibility to use `unknown`.
As `any` skips any type checking by the TS compiler, the compiler yells at us to not use it but there's a catch with `unknown` too which is that it needs to be asserted to a certain type before performing any operation on it.

`movex\libs\movex-core-util\src\lib\core-util\types.ts`

image

**Comment by GabrielCTroia** [comment]
Aha, I see! I think in that case it should be `any`, but I'm curious is the compiler failing if you pass `unknown`?

**Comment by Rounak-stha** [comment]
> Aha, I see! I think in that case it should be `any`, but I'm curious is the compiler failing if you pass `unknown`?

Hey, sorry for the late reply. No, it does not fail on `unkown`.

**Comment by GabrielCTroia** [comment]
No worries, I think this will need another issue once we are ready to tackle the linting warnings :)

**Pull request merged**
