### PR TITLE
Disable eslint rule for bin file

### PR DESCRIPTION
**Pull request by techemmy**
Resolves issue #105

### CODE REVIEW

**Comment by GabrielCTroia** [comment]
Hey @techemmy see my comment here https://github.com/movesthatmatter/movex/pull/92#issuecomment-1758453951

**Comment by techemmy** [comment]
> Hey @techemmy please see my comment here [#92 (comment)](https://github.com/movesthatmatter/movex/pull/92#issuecomment-1758453951). These commits still seem to be unsigned/unverified.

Yeah, I've seen it. I working to fix the issue with signing now.

**Comment by techemmy** [comment]
@GabrielCTroia I think it's signed now.

**Comment by GabrielCTroia** [comment]
Hey @techemmy, yes it seems to be signed now, but only the last commit unfortunately 😔! 

I can merge it like this no problem, but I'm not sure all the changes will be counted for hactoberfest.

My suggestion is to open a new branch off of `main` and `cherry-pick` the last (verified) commit. See a quick guide to cherry pick here if you need help https://stackoverflow.com/a/9339460/2093626.

Let me know if this works for you or wether you want me to merge it as is! 🙌

**Comment by techemmy** [comment]
I think we should merge like that

**Comment by GabrielCTroia** [comment]
Ok no worries @techemmy. Merging now! 🎉

One lsat thing, could you please give us a star so we can bump Movex in the ranking hacktoberfest rankings!🙏

**Pull request merged**
