### PR TITLE
Fix "[project] Duplicate the libs/movex/Readme.md at root #137"

### PR DESCRIPTION
**Pull request by jude-san**

### CODE REVIEW

**Comment by GabrielCTroia** [comment]
Hey @jude-san thank you for your PR. It seems like the CI jobs are failing with this error
Screenshot 2023-10-16 at 1 35 09 PM

Please see this answer https://stackoverflow.com/a/18419800/2093626 on how to fix it. Since the initial Readme was a symlink that needs to be reverted back to regular file! 

Let me know if you need any help with it! 🙏

**Comment by jude-san** [comment]
> Hey @jude-san thank you for your PR. It seems like the CI jobs are failing with this error Screenshot 2023-10-16 at 1 35 09 PM
> 
> Please see this answer https://stackoverflow.com/a/18419800/2093626 on how to fix it. Since the initial Readme was a symlink that needs to be reverted back to regular file!
> 
> Let me know if you need any help with it! 🙏

Noted, thanks for the feedback.

**Comment by jude-san** [comment]
HI @GabrielCTroia  I need your help with these commits [a17c3cb](https://github.com/movesthatmatter/movex/pull/156/commits/a17c3cb11eea8ccafe18d9021c077350b4015253), [54963f2](https://github.com/movesthatmatter/movex/pull/156/commits/54963f2ab2efca7c762c1fec4090c9fe4d1ebb0d), and [3a56879](https://github.com/movesthatmatter/movex/pull/156/commits/3a56879ff46725d5c6b9436267f9fd250812c9b5). I pushed it before I verified my account using gpg keys.

**Comment by GabrielCTroia** [comment]
Hey @jude-san, the way you can verify those commits is to rebase your branch now on top of master, just so the commits get signed, now that gpg is setup. Then you can force push the branch again. 

See this answer https://stackoverflow.com/a/15667644/2093626, and I would do something like `git rebase --signoff 8e49387`

**Comment by jude-san** [comment]
> HI @GabrielCTroia I need your help with these commits [a17c3cb](https://github.com/movesthatmatter/movex/pull/156/commits/a17c3cb11eea8ccafe18d9021c077350b4015253), [54963f2](https://github.com/movesthatmatter/movex/pull/156/commits/54963f2ab2efca7c762c1fec4090c9fe4d1ebb0d), and [3a56879](https://github.com/movesthatmatter/movex/pull/156/commits/3a56879ff46725d5c6b9436267f9fd250812c9b5). I pushed it before I verified my account using gpg keys.

HI @GabrielCTroia is it possible to close this PR and start over?, since my commits are causing merging issues.

**Comment by GabrielCTroia** [comment]
Yes of course @jude-san no worries! Ideally you can open a PR per issue but whatever feels easier for you! Let me know if you need help with anyhting

**Pull request closed without merging**
