### PR TITLE
refactor: :recycle: fix_Self_Refencing_Absolute_Imports

### LINKED ISSUE #37: [libs/movex] - Remove self referencing absolute imports
# Where

`/libs/movex`

# What

There are a few imports that are directly referencing the absolute "movex" path (i.e. from node_modules) instead of importing from a relative path, since it's within it's directory!

See the culprit files here:
Screenshot 2023-10-06 at 6 52 55 PM

# Why
This is not ideal because it can create more importing issues down the road. It's also not necessary!

# Definition of done

- All the absolute imports aka `import { my_file } from 'movex'` is changed to `import { my_file } from './path/to/my_file'`
- Note, these only refers to imports from 'movex' not any of the other libraries such as 'movex-react', 'movex-core-util', etc.

### PR DESCRIPTION
**Pull request by Rounak-stha**
Fixes #37

### CODE REVIEW

**Comment by GabrielCTroia** [comment]
Thank you @Rounak-stha! This is ready to merge! 🚀🎉

One last thing, could you give us a star pls so we can bump up the repo?! Cheers 🙏

**Comment by Rounak-stha** [comment]
Great .
You've got a star. ⭐

**Comment by GabrielCTroia** [comment]
> Great . You've got a star. ⭐

Thank you sir!

**Comment by GabrielCTroia** [comment]
May I also ask you, if you have any feedback about the project. Is it clear what it does? Did you understand the docs, etc? Do you have any questions?

**Comment by Rounak-stha** [comment]
First of all, the project's awesome.
I'm still going through the docs and from what I've gathered, the docs are explanatory and I really liked how ideas and techniques used underneath is mentioned and summarized, it really helps contributors get started .
I'm finding the project really interesting and am planning to investigate further to contribute.

**Comment by GabrielCTroia** [comment]
> First of all, the project's awesome. I'm still going through the docs and from what I've gathered, the docs are explanatory and I really liked how ideas and techniques used underneath is mentioned and summarized, it really helps contributors get started . I'm finding the project really interesting and am planning to investigate further to contribute.

Thank you so much for saying that! I did put a lot of work in it, and am really excited to see people like you appreciating it and offering their help! If you have any question or need help with anything don't hesitate to ping me! You can also join our discord if you haven't yet!

Thank you @Rounak-stha 🙏

**Pull request merged**
