### PR TITLE
fix: add tsc config info to fix issue #100

### PR DESCRIPTION
**Pull request by techemmy**

### CODE REVIEW

**Comment by techemmy** [comment]
@GabrielCTroia you closed the issue, but you didn't merge it?

**Comment by GabrielCTroia** [comment]
Oh shoot, I didn't realize this still had the `movex/project.json` tsc command In. The `movex-server/project` is already merged though 🧐

Could you please open a new PR with that 🙏

**Comment by techemmy** [comment]
> Oh shoot, I didn't realize this still had the `movex/project.json` tsc command In. The `movex-server/project` is already merged though 🧐
> 
> Could you please open a new PR with that 🙏

I don't understand. Open a PR on?

**Comment by GabrielCTroia** [comment]
Hey @techemmy, I went back and rechecked what's currently in `main` and your code is already in - I'm a bit confused too what happened but it got already merged – didn't you open the same PR twice due to commit verification issues?

Here's the git blame on the file:
Screenshot 2023-10-17 at 5 44 26 PM

**Comment by techemmy** [comment]
Yeah,  I think so. That means the issue is fixed then 💯

**Pull request merged**
