### PR TITLE
Added delete test

### PR DESCRIPTION
**Pull request by vishalda**
Closes issue: #45 
- [x] Have added test for remove() method

### CODE REVIEW

**Comment by GabrielCTroia** [comment]
Thank you @vishalda! 

What happens when you try to delete a non existent item? Should we not test that too? 🤔

**Comment by GabrielCTroia** [comment]
Also, please sign your commits so I can merge them once ready. Check this tutorial out https://docs.github.com/articles/about-gpg/

**Comment by GabrielCTroia** [comment]
Hmm, the interface expects to return a `ResourceInexistentError`:
Screenshot 2023-10-10 at 12 36 09 PM

but the implementation skipped over that from what it seems:
Screenshot 2023-10-10 at 12 35 06 PM

Would you like to implement that too? If not I can open another issue. Thank you!

**Comment by vishalda** [comment]
Yes I would like to try

**Pull request merged**
