### PR TITLE
Removed unused interface

### LINKED ISSUE #139: [movex-core-util] Remove unused `EmitterEventMap` interface
# Where

`libs/movex-core-util/src/lib/core-util/EventEmitter.ts`

# What

Remove the `EmitterEventMap` on the last line

# Why 
It's not used anymore and it throws a linting error

# Definition of done
- the interface is removed EmitterEventMap

### PR DESCRIPTION
**Pull request by sotiriszogos**
Fixed #139

### CODE REVIEW

**Comment by GabrielCTroia** [comment]
Thank you @sotiriszogos! I'm about to merge your PR but before I can do so, could you please sign your commit using this tutorial https://docs.github.com/articles/about-gpg/, so github can track your contribution for #hacktoberfest correctly! 🙌

**Comment by sotiriszogos** [comment]
Hello @GabrielCTroia. Is this procedure necessary? I had participated last year without doing that and I had no issues

**Comment by GabrielCTroia** [comment]
It's up to you @sotiriszogos, but from what I know so far with other contributors it does help! 

It's pretty simple – you can add the SSH or GPG to your git locally and then you interactively rebase you branch, or just `git commit amend` since you only have one commit.

Or, just let me know if you'd rather do it without and i can merge it! 🙌

**Comment by sotiriszogos** [comment]
Hello @GabrielCTroia, thank you for your suggestion, but because I have very limited time, if it is fine for your side, please proceed with the merge without this verification thing. Thank you again !

**Comment by GabrielCTroia** [comment]
I merged it @sotiriszogos! Thank you for letting me know and for your effort! 

**One last thing, could you please give us a star so we can bump the repo up a bit! 🙏**

Thank you again and hope to see you around soon!

**Pull request merged**
